site_name: Ing. Petr Kratochvíl
theme:
  name: material
  logo: assets/Petr-Kratochvil/DSCN0104-cut01-edit02-cut01.jpg
  favicon: assets/Petr-Kratochvil/DSCN0104-cut01-edit02-cut01.jpg
  include_sidebar: false
  custom_dir: './overrides'
use_directory_urls: true
extra:
  languages:
    - 'cs/cv': 'cs'
  generator: false
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.magiclink:
      repo_url_shorthand: true
      social_url_shorthand: true
      normalize_issue_symbols: true
extra_css:
  - './assets/common.css'
repo_url: 'https://github.com/kratocz/'
plugins:
  - redirects:
      redirect_maps:
        'cs/zivotopis.md': 'cs/cv.md'
        'cs/kontakt.md': 'index.md'
        '**.md': 'index.md'
nav:
  - 'Intro': 'index.md'
  - 'en/cv.md'
  - 'cs/cv.md'
  - 'pl/cv.md'
